[package]
name = "cosmic-widgets-applet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
cw-core = { path = "../cw-core" }
zbus.workspace = true

[lints]
workspace = true

